### ISSUE TITLE
Issue with the code

### ISSUE THREAD

**Issue by SharonGao1992** [huaying/instagram-crawler#112]
Does anyone meet the same problem as me?
When I try to crawl data using the author's commands, it shows this error:
line 104, in get_user_profile
    post_num, follower_num, following_num = statistics
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by SuhyunL** [comment]
> Does anyone meet the same problem as me?
> When I try to crawl data using the author's commands, it shows this error:
> line 104, in get_user_profile
> post_num, follower_num, following_num = statistics
> ValueError: not enough values to unpack (expected 3, got 0)

Did you solve it? I'm facing the same problem.
