### ISSUE TITLE
i got log problem

### ISSUE THREAD

**Issue by anakmalank** [huaying/instagram-crawler#12]
hi Huaying, i got problem that log file was not found.
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/instagram-crawler-1538195382.log'
Exception ignored in: <function Logging.__del__ at 0x02C62270>
Traceback (most recent call last):
  File "D:\ARIEF\CRAWLIG2\inscrawler\crawler.py", line 37, in __del__
    self.logger.close()
AttributeError: 'InsCrawler' object has no attribute 'logger'
![image](https://user-images.githubusercontent.com/20079996/46241207-82e79e80-c369-11e8-9128-1162cb5c06cd.png)

**Comment by huaying** [comment]
Hi, thanks for the feedback.

Window 10 doesn't have the directory `/tmp`, which causes the problem.
Will work on it soon.

**Comment by huaying** [comment]
Just ignore the log when can't find the path. Win 10 should work with the latest version
