### ISSUE TITLE
"stale element reference: element is not attached to the page document"

### ISSUE THREAD

**Issue by t510599** [huaying/instagram-crawler#14]
![screenshot from 2018-10-09 17-40-26](https://user-images.githubusercontent.com/18533304/46660861-8e995780-cbea-11e8-8bd1-1b695800bc1d.png)

**Comment by t510599** [comment]
chrome 69.0.3497.100
chromedriver 2.42.591071
python 3.6.5
selenium 3.9.0

tested on arch linux

**Comment by huaying** [comment]
It seems that you were able to run the program. (https://github.com/huaying/instagram-crawler/issues/10)
Does this issue happen after you pulled the latest version? or you run the program on another device?

**Comment by t510599** [comment]
Same device as #10, but the newest version

**Comment by huaying** [comment]
I just tested it in 2 different linux machines and they both worked. Can you try to use another machine to see if the same error would show up?

**Comment by t510599** [comment]
![default](https://user-images.githubusercontent.com/18533304/46904784-316c1180-cf1c-11e8-8a56-6f8ae7e9ce5d.png)
It still threw the same error.
Tested on ubuntu 16.04

I also tried with `--debug` option, and it seemed that the error occurred when getting url of image.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18533304/46905038-2c10c600-cf20-11e8-860e-d804ba2e125b.gif)

**Comment by huaying** [comment]
It's weird lol. I can't reproduce it in any of my machines...

The website might be different due to A/B testing. I am not sure though.
If you really need to make it work, email me with your contact. I can help you debug :)
