### ISSUE TITLE
Couldn't automatically log in

### ISSUE THREAD

**Issue by bingdboujee** [huaying/instagram-crawler#21]
Hi I'm new to python,
when I put my instagram username as 'bingdnboujee' and password in secret.py
seems like it didn't work, the code recognized my username as 'bingd', which is my windows system user name.

**Comment by huaying** [comment]
Sorry for the late reply. 
Your env variable `USERNAME` might has value already.

Please try to modify the line  in `secret.py` 
`username = os.environ.get('USERNAME', '')` to 
`username = 'bingdnboujee' `
