### ISSUE TITLE
How to go to the next post if one of the post can't load

### ISSUE THREAD

**Issue by ihcsankml** [huaying/instagram-crawler#24]
Hi Huaying,

I have a problem, if the internet connection is slow. When the i use the post_full, crawler trying to get the some post, but suddenly one of the post didn't load, and it suddenly return an error because it can't get the None Type element. 

Is there any way to overcome it by going to the next Post if its return None? I already tried to edit the wait time parameter to 120 in findone method, but its same, the post just can't be loaded and in the end return None Type object.

Thank you

**Comment by huaying** [comment]
Yeah It might be a good suggestion. 
For now, if you want to recover the data that you already crawled, you can try to find it from `/tmp/instagram-crawler-{TIMESTAMP}`. The data format might be different though.

**Comment by huaying** [comment]
close this because we actually can't go to next post if the current post couldn't be loaded
