### ISSUE TITLE
Is it possible to fetch the number of likes of each post as well?

### ISSUE THREAD

**Issue by jad1s** [huaying/instagram-crawler#25]
as subject. thanks!

**Comment by huaying** [comment]
I haven’t taken a look but I feel like it’s possible. Thanks for the suggestion.

**Comment by jad1s** [comment]
Thanks for the reply! I will be super excited to see the feature become real!

**Comment by juanjovazpar** [comment]
I implemented something that may help you

https://github.com/huaying/instagram-crawler/pull/27
