### ISSUE TITLE
posts_full Not working

### ISSUE THREAD

**Issue by goursandesh** [huaying/instagram-crawler#30]
tried for multiple user profiles,

next_key = ele_a_datetime.get_attribute('href')
AttributeError: 'NoneType' object has no attribute 'get_attribute'
Exception KeyError: KeyError(<weakref at 0x10b479f18; to 'tqdm' at 0x10b443a90>,) in  ignored

**Comment by huaying** [comment]
It happened when you have slow network. It's fixed in https://github.com/huaying/instagram-crawler/commit/56cc3554fdfc9c193277035a09dc08e3d69ecd28
