### ISSUE TITLE
Cant run script

### ISSUE THREAD

**Issue by petersg** [huaying/instagram-crawler#41]
I follow the instalation guide but when i try to launch it i get this:

Traceback (most recent call last):
  File "crawler.py", line 3, in <module>
    from builtins import open
ImportError: No module named builtins

**Comment by Regina21** [comment]
I also have a problem when running the script. My output looks as followed: 
`(base) D:\Github\instagram-crawler-master\instagram-crawler-master>python crawler.py posts_full -u cal_foodie -n 100 -o ./output


Traceback (most recent call last):
  File "crawler.py", line 5, in <module>
    from inscrawler import InsCrawler
  File "D:\Github\instagram-crawler-master\instagram-crawler-master\inscrawler\__init__.py", line 1, in <module>
    from .crawler import InsCrawler
  File "D:\Github\instagram-crawler-master\instagram-crawler-master\inscrawler\crawler.py", line 15, in <module>
    from . import secret
ImportError: cannot import name 'secret' from 'inscrawler' (D:\Github\instagram-crawler-master\instagram-crawler-master\inscrawler\__init__.py)
`

**Comment by mrdangran** [comment]
use python3 , it fixed those issues for me

**Comment by kswgit** [comment]
Did you have the issue yet? @petersg 
I hope you solved problems.

**Comment by qvintillion** [comment]
I'm having the same issue, repeated the same steps on my Macbook and it works perfectly using python3. In Anaconda 3 on my Windows machine, however, using "python" results in the OP's error, "python3" just runs immediately and doesn't fetch or output anything
