### ISSUE TITLE
Log in for private accounts

### ISSUE THREAD

**Issue by lizasivriver** [huaying/instagram-crawler#53]
How do I enter in the username and password in secret.py? I am getting errors that there is no username and password after I directly edit secret.py. I am also running the cp inscrawler/secret.py.dist inscrawler/secret.py command after I edit.

**Comment by huaying** [comment]
The program reads acct/passwd from `inscrawler/secret.py`. Execute `cp inscrawler/secret.py.dist inscrawler/secret.py` and put your acct/passwd in `inscrawler/secret.py`.
