### ISSUE TITLE
[pip  install -r requirements.txt] error

### ISSUE THREAD

**Issue by inhyek** [huaying/instagram-crawler#63]
I have no idea why this error occured. 
I have visited the official site below, and checked newest version. It was 19.3b0. 
https://pypi.org/project/black/

===================error message==============================
Collecting black==19.3b0 (from -r requirements.txt (line 5))
  ERROR: Could not find a version that satisfies the requirement black==19.3b0 (from -r requirements.txt (line 5)) (from versions: none)
ERROR: No matching distribution found for black==19.3b0 (from -r requirements.txt (line 5))

**Comment by vocuzi** [comment]
It requires Python 3.6.0+ to run.

**Comment by yairvogel** [comment]
you were probably using python 2.x
