### ISSUE TITLE
Crawling always fails at the 9th post!

### ISSUE THREAD

**Issue by Raki22** [huaying/instagram-crawler#72]
I installed the crawler on my machine all working well, until the crawling reaches the 9th post to be crawled it fails. 

I tried changing the target user still the same problem

I also changed the number of posts but no response. 

the raised error:    Failed to fetch the post: https://www.instagram.com/p/B6oEe2rnjIu/

**Comment by bobmarley29** [comment]
Had same problem. I've tried different repo https://github.com/drawrowfly/instagram-scraper works great so far

**Comment by Raki22** [comment]
thank you so much
